name: Deploy Hyperswitch App
run-name: "Deploy: Hyperswitch App - ${{ inputs.version_tag }} [${{ inputs.environment }}]"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        type: choice
        options:
        - 'Integ'
        - 'Sandbox'
        default: 'Integ'
      version_tag:
        description: 'Version Tag'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: install yq
        run: |
            mkdir -p ${{ github.workspace }}/bin
            wget -qO ${{ github.workspace }}/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64
            chmod +x ${{ github.workspace }}/bin/yq
            echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: check
        run: |
            cat <<EOF > sample.json
            {
                "glossary": {
                    "title": "example glossary",
            		"GlossDiv": {
                        "title": "S",
            			"GlossList": {
                            "GlossEntry": {
                                "ID": "SGML",
            					"SortAs": "SGML",
            					"GlossTerm": "Standard Generalized Markup Language",
            					"Acronym": "SGML",
            					"Abbrev": "ISO 8879:1986",
            					"GlossDef": {
                                    "para": "A meta-markup language, used to create markup languages such as DocBook.",
            						"GlossSeeAlso": ["GML", "XML"]
                                },
            					"GlossSee": "markup"
                            }
                        }
                    }
                }
            }
            EOF
            yq -Poy sample.json
            
