name: Deploy Hyperswitch App
run-name: "Deploy: Hyperswitch App - ${{ inputs.version_tag }} [${{ inputs.environment }}]"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment'
        required: true
        type: choice
        options:
        - 'Integ'
        - 'Sandbox'
        default: 'Integ'
      version_tag:
        description: 'Version Tag'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: install yq
        run: |
            wget -qO yq https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64
            chmod +x yq

      - name: check
        run: |
            yq -v
            
